
import React, { useState } from 'react';
import { User } from '../../types';
import { Stack, Typography, Section, Button, Card } from '../design-system/Primitives';
import { Logo } from '../brand/Logo';
import { editProfileImage } from '../../services/geminiService';
import { jsPDF } from 'jspdf';

interface ProfileViewProps {
  user: User;
  onUpdateUser: (user: User) => void;
  onLogout: () => void;
}

const ProfileView: React.FC<ProfileViewProps> = ({ user, onUpdateUser, onLogout }) => {
  const [isEditing, setIsEditing] = useState(false);
  const [isAiStudioOpen, setIsAiStudioOpen] = useState(false);
  const [aiPrompt, setAiPrompt] = useState('');
  const [isAiLoading, setIsAiLoading] = useState(false);
  
  const [tempBio, setTempBio] = useState(user.bio);
  const [tempWork, setTempWork] = useState(user.work || '');
  const [tempLocation, setTempLocation] = useState(user.location);
  const [tempEducation, setTempEducation] = useState(user.education || '');
  const [tempInterests, setTempInterests] = useState(user.interests?.join(', ') || '');
  const [tempHobbies, setTempHobbies] = useState(user.hobbies?.join(', ') || '');

  const handleSave = () => {
    onUpdateUser({
      ...user,
      bio: tempBio,
      work: tempWork,
      location: tempLocation,
      education: tempEducation,
      interests: tempInterests.split(',').map(s => s.trim()).filter(Boolean),
      hobbies: tempHobbies.split(',').map(s => s.trim()).filter(Boolean),
    });
    setIsEditing(false);
  };

  const handleCancel = () => {
    setTempBio(user.bio);
    setTempWork(user.work || '');
    setTempLocation(user.location);
    setTempEducation(user.education || '');
    setTempInterests(user.interests?.join(', ') || '');
    setTempHobbies(user.hobbies?.join(', ') || '');
    setIsEditing(false);
  };

  const handleAiEdit = async () => {
    if (!aiPrompt) return;
    setIsAiLoading(true);
    const newImage = await editProfileImage(user.avatar, aiPrompt);
    if (newImage) {
      onUpdateUser({ ...user, avatar: newImage });
      setIsAiStudioOpen(false);
      setAiPrompt('');
    }
    setIsAiLoading(false);
  };

  const handleExportPdf = () => {
    const doc = new jsPDF();
    const margin = 20;
    let y = 30;

    // Header
    doc.setFontSize(24);
    doc.setTextColor(99, 102, 241); // indigo-500
    doc.text("CIRCLO", margin, y);
    doc.setFontSize(10);
    doc.setTextColor(150, 150, 150);
    doc.text("IDENTITY VAULT EXPORT", 190, y, { align: 'right' });
    
    y += 15;
    doc.setDrawColor(230, 230, 230);
    doc.line(margin, y, 190, y);
    
    y += 20;
    doc.setFontSize(18);
    doc.setTextColor(30, 30, 30);
    doc.text(user.name.toUpperCase(), margin, y);
    
    y += 10;
    doc.setFontSize(11);
    doc.setTextColor(100, 100, 100);
    doc.text(`${user.role} | ${user.location}`, margin, y);

    y += 20;
    doc.setFontSize(10);
    doc.setTextColor(150, 150, 150);
    doc.text("WORK", margin, y);
    y += 7;
    doc.setFontSize(12);
    doc.setTextColor(30, 30, 30);
    doc.text(user.work || "Not specified", margin, y);

    y += 15;
    doc.setFontSize(10);
    doc.setTextColor(150, 150, 150);
    doc.text("EDUCATION", margin, y);
    y += 7;
    doc.setFontSize(12);
    doc.setTextColor(30, 30, 30);
    doc.text(user.education || "Not specified", margin, y);

    y += 15;
    doc.setFontSize(10);
    doc.setTextColor(150, 150, 150);
    doc.text("BIO", margin, y);
    y += 7;
    doc.setFontSize(12);
    doc.setTextColor(50, 50, 50);
    const splitBio = doc.splitTextToSize(user.bio, 160);
    doc.text(splitBio, margin, y);
    y += (splitBio.length * 7);

    y += 10;
    doc.setFontSize(10);
    doc.setTextColor(150, 150, 150);
    doc.text("SIGNALS & INTERESTS", margin, y);
    y += 7;
    doc.setFontSize(11);
    doc.setTextColor(30, 30, 30);
    const allSignals = [...(user.interests || []), ...(user.hobbies || [])].join(", ");
    const splitSignals = doc.splitTextToSize(allSignals, 160);
    doc.text(splitSignals, margin, y);

    // Footer
    doc.setFontSize(8);
    doc.setTextColor(200, 200, 200);
    doc.text("Generated by Circlo Private Ledger. Verified Identity Node Export.", margin, 280);

    doc.save(`Circlo_Identity_${user.name.replace(/\s+/g, '_')}.pdf`);
  };

  const triggerEdit = () => {
    if (!isEditing) setIsEditing(true);
  };

  return (
    <Section className="flex-1 flex flex-col p-10 animate-fade-in overflow-y-auto no-scrollbar pb-40">
      <Stack gap={12}>
        <Stack gap={2} className="flex flex-row justify-between items-end">
          <Stack gap={2}>
            <Typography.Meta className="text-indigo-400">Identity Vault</Typography.Meta>
            <Typography.Heading>Circle.</Typography.Heading>
          </Stack>
          {!isEditing && (
            <button 
              onClick={() => setIsEditing(true)}
              className="mb-1 text-[10px] font-black uppercase tracking-widest text-indigo-500 hover:text-white transition-colors"
            >
              Modify Profile
            </button>
          )}
        </Stack>

        <Stack gap={8} align="center" className="py-8 border-b border-slate-900">
          <div className="relative group">
            <img src={user.avatar} className="w-32 h-32 rounded-[3.5rem] object-cover border-4 border-slate-900 shadow-2xl transition-all" alt="" />
            <button 
              onClick={() => setIsAiStudioOpen(!isAiStudioOpen)}
              className="absolute -bottom-2 -right-2 w-10 h-10 bg-indigo-600 rounded-2xl flex items-center justify-center text-white shadow-lg hover:bg-indigo-500 transition-colors z-20"
            >
              <i className={`fas ${isAiStudioOpen ? 'fa-times' : 'fa-wand-magic-sparkles'}`}></i>
            </button>
          </div>
          
          {isAiStudioOpen && (
            <Card variant="glass" className="w-full p-6 animate-fade-in">
              <Stack gap={4}>
                <Typography.Meta>AI Image Studio</Typography.Meta>
                <div className="space-y-2">
                  <input 
                    value={aiPrompt}
                    onChange={(e) => setAiPrompt(e.target.value)}
                    placeholder="e.g. 'Add a retro film filter' or 'Remove bg'"
                    className="w-full bg-slate-950 border border-slate-800 rounded-2xl p-4 text-xs text-white outline-none focus:border-indigo-500 transition-colors"
                  />
                  <Button onClick={handleAiEdit} disabled={isAiLoading || !aiPrompt} className="w-full py-4 text-[10px]">
                    {isAiLoading ? (
                      <span className="flex items-center gap-2"><i className="fas fa-spinner animate-spin"></i> Processing...</span>
                    ) : 'Generate & Update'}
                  </Button>
                </div>
              </Stack>
            </Card>
          )}

          <Stack gap={2} align="center" className="w-full">
            <Typography.Subheading className="text-white text-3xl font-black">{user.name}</Typography.Subheading>
            {isEditing ? (
              <input 
                value={tempLocation}
                onChange={(e) => setTempLocation(e.target.value)}
                placeholder="Current City"
                className="w-full bg-slate-950 border border-slate-800 rounded-xl px-4 py-2 text-center text-[10px] font-black uppercase tracking-[0.2em] text-indigo-400 focus:border-indigo-500 outline-none"
              />
            ) : (
              <button onClick={triggerEdit} className="group flex items-center gap-2">
                <Typography.Meta className="group-hover:text-indigo-400 transition-colors cursor-pointer">
                  {user.role} • {user.location} <i className="fas fa-pencil text-[8px] opacity-0 group-hover:opacity-100 ml-1 transition-opacity"></i>
                </Typography.Meta>
              </button>
            )}
          </Stack>
        </Stack>

        <Card variant="glass" className="relative">
          <Stack gap={8}>
            <Stack gap={4}>
              <Typography.Meta>Story & Origins</Typography.Meta>
              {isEditing ? (
                <Stack gap={4}>
                  <textarea 
                    value={tempBio}
                    onChange={(e) => setTempBio(e.target.value)}
                    placeholder="Tell your unfiltered story..."
                    className="w-full bg-slate-950 border border-slate-800 rounded-3xl p-6 text-sm text-slate-300 outline-none min-h-[120px] focus:border-indigo-500 transition-colors resize-none"
                  />
                  <div className="relative">
                    <i className="fas fa-briefcase absolute left-5 top-1/2 -translate-y-1/2 text-slate-600 text-sm"></i>
                    <input 
                      value={tempWork}
                      onChange={(e) => setTempWork(e.target.value)}
                      placeholder="WORK (e.g. Scaling systems)"
                      className="w-full bg-slate-950 border border-slate-800 rounded-2xl pl-12 pr-6 py-4 text-sm text-slate-300 outline-none focus:border-indigo-500 transition-colors"
                    />
                  </div>
                  <div className="relative">
                    <i className="fas fa-graduation-cap absolute left-5 top-1/2 -translate-y-1/2 text-slate-600 text-sm"></i>
                    <input 
                      value={tempEducation}
                      onChange={(e) => setTempEducation(e.target.value)}
                      placeholder="Education / Background"
                      className="w-full bg-slate-950 border border-slate-800 rounded-2xl pl-12 pr-6 py-4 text-sm text-slate-300 outline-none focus:border-indigo-500 transition-colors"
                    />
                  </div>
                </Stack>
              ) : (
                <button onClick={triggerEdit} className="text-left group block w-full">
                  <Stack gap={4}>
                    <Typography.Body className="text-slate-200 group-hover:text-white transition-colors">
                      {user.bio}
                    </Typography.Body>
                    <div className="flex flex-col gap-2">
                      <div className="flex items-center gap-2 text-slate-500 group-hover:text-indigo-400 transition-colors">
                        <i className="fas fa-briefcase text-xs"></i>
                        <Typography.Meta className="normal-case tracking-normal">WORK: {user.work || "Founder"}</Typography.Meta>
                      </div>
                      <div className="flex items-center gap-2 text-slate-500 group-hover:text-indigo-400 transition-colors">
                        <i className="fas fa-graduation-cap text-xs"></i>
                        <Typography.Meta className="normal-case tracking-normal">{user.education || "Verified Individual"}</Typography.Meta>
                      </div>
                    </div>
                  </Stack>
                </button>
              )}
            </Stack>

            <Stack gap={4}>
              <Typography.Meta>Signals & Frequency</Typography.Meta>
              {isEditing ? (
                <Stack gap={4}>
                  <div className="space-y-1">
                    <label className="text-[9px] font-black uppercase text-slate-600 ml-2">Interests</label>
                    <input 
                      value={tempInterests}
                      onChange={(e) => setTempInterests(e.target.value)}
                      placeholder="AI, Art, Fitness..."
                      className="w-full bg-slate-950 border border-slate-800 rounded-2xl p-4 text-sm text-slate-300 outline-none focus:border-indigo-500 transition-colors"
                    />
                  </div>
                  <div className="space-y-1">
                    <label className="text-[9px] font-black uppercase text-slate-600 ml-2">Hobbies</label>
                    <input 
                      value={tempHobbies}
                      onChange={(e) => setTempHobbies(e.target.value)}
                      placeholder="Surfing, Cooking, Reading..."
                      className="w-full bg-slate-950 border border-slate-800 rounded-2xl p-4 text-sm text-slate-300 outline-none focus:border-indigo-500 transition-colors"
                    />
                  </div>
                </Stack>
              ) : (
                <button onClick={triggerEdit} className="text-left group flex flex-wrap gap-2">
                  {[...(user.interests || []), ...(user.hobbies || [])].length > 0 ? (
                    [...(user.interests || []), ...(user.hobbies || [])].map((tag, i) => (
                      <span key={i} className="px-3 py-1.5 bg-indigo-500/5 border border-indigo-500/10 rounded-xl text-[9px] font-black uppercase text-indigo-400 group-hover:border-indigo-500/30 transition-all">
                        {tag}
                      </span>
                    ))
                  ) : (
                    <span className="text-[10px] text-slate-600 italic">Add your unique signals...</span>
                  )}
                </button>
              )}
            </Stack>
          </Stack>
        </Card>

        {isEditing ? (
          <Stack gap={4} className="mt-4">
            <Button onClick={handleSave} variant="secondary" className="w-full py-8 text-white shadow-indigo-600/20 shadow-xl">
              Sync Updates
            </Button>
            <Button onClick={handleCancel} variant="subtle" className="w-full py-6">
              Discard Changes
            </Button>
          </Stack>
        ) : (
          <Stack gap={4} className="mt-4">
            <Button onClick={handleExportPdf} variant="subtle" className="w-full flex justify-between group">
              Vault Export <i className="fas fa-download opacity-30 group-hover:opacity-100 transition-opacity"></i>
            </Button>
            <Button onClick={onLogout} className="w-full border-rose-500/10 text-rose-500 hover:bg-rose-500 hover:text-white transition-all" variant="subtle">
              Revoke Identity Node
            </Button>
          </Stack>
        )}
      </Stack>
    </Section>
  );
};

export default ProfileView;
